apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "order-deployment-config"
  namespace: "default"
  labels:
    app: "order"
data:
  STOCK_UPDATE_TOPIC: "target-stock-update-gke"
  PORT: "8080"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "order-deployment"
  namespace: "default"
  labels:
    app: "order"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "order"
  template:
    metadata:
      labels:
        app: "order"
    spec:
      serviceAccountName: "k8s-service-account"
      containers:
      - name: "order-service"
        image: "gcr.io/serverless-k8s-study/order-service"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "768Mi"
            cpu: "750m"
        ports:
          - containerPort: 8080
        env:
        - name: "STOCK_UPDATE_TOPIC"
          valueFrom:
            configMapKeyRef:
              key: "STOCK_UPDATE_TOPIC"
              name: "order-deployment-config"
        - name: "DATABASE_HOST"
          valueFrom:
            secretKeyRef:
              key: "DATABASE_HOST"
              name: "db-config-secret"
        - name: "DATABASE_USER"
          valueFrom:
            secretKeyRef:
              key: "DATABASE_USER"
              name: "db-config-secret"
        - name: "DATABASE_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "DATABASE_PASSWORD"
              name: "db-config-secret"
        - name: "PORT"
          valueFrom:
            configMapKeyRef:
              key: "PORT"
              name: "order-deployment-config"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "order-service"
  namespace: "default"
  labels:
    app: "order"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "order"
  type: "ClusterIP"
---
apiVersion: autoscaling/v2
kind: "HorizontalPodAutoscaler"
metadata:
  name: "order-service-hpa"
  namespace: "default"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
